version: '3.6'

services:

  api:
    image: node:10.15.3-alpine
    container_name: tqd-node
    build: ./app
    ports:
      - 8080:8080 
    environment:
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - NODE_PORT=8080
     - ELASTIC_URL=http://elasticsearch:9200
    volumes:
      - ./app/:/usr/src/app/
    command: npm run start
    links:
        - elasticsearch
    depends_on:
        - elasticsearch
    networks: 
      - esnet

  elasticsearch:
    container_name: tqd-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    env_file:
      - elastic/elastic.env
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200
    networks: 
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    env_file:
      - kibana/kibana.env
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

networks:
  esnet:
volumes:
  esdata: